#pragma once

#ifdef AUDIO_ENABLE
#define AUDIO_PWM_CHANNEL RP2040_PWM_CHANNEL_B
#define AUDIO_PWM_DRIVER PWMD4
#define AUDIO_STATE_TIMER GPTD4
#define NO_MUSIC_MODE
#define STARTUP_SONG SONG(STARTUP_SOUND)
#endif

#define AUDIO_PIN B5
#define EE_HANDS
#define ENCODER_RESOLUTION 2

#ifdef POINTING_DEVICE_ENABLE
#define POINTING_DEVICE_RIGHT
#define POINTING_DEVICE_ROTATION_180
#define SPLIT_POINTING_ENABLE
#endif

#define SPLIT_LAYER_STATE_ENABLE
#define SPLIT_LED_STATE_ENABLE
#define SPLIT_WPM_ENABLE
#define TAP_CODE_DELAY 10
#define USE_SERIAL_PD2
